version: '3.7'

services:

  nghien-cuu-khoa-hoc:
    image: nghien-cuu-khoa-hoc
    hostname: nghien-cuu-khoa-hoc
    environment:
      - KAFKA_SERVERS=kafka:9092
      - DISCOVERY_SERVICE_ADDRESS=http://eureka:8761/eureka
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - ACTIVE_PROFILE=dev
      - OAUTH_SERVICE=http://oauth2-service:8080
      - OAUTH-SECRET = secret
    volumes:
      - /home/thangpx/nghien-cuu-khoa-hoc/uploads:/uploads
      - /home/thangpx/nghien-cuu-khoa-hoc/downloads:/downloads
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      endpoint_mode: dnsrr #dns round robbin
    networks:
      - app-net

networks:
  app-net:
    external: true
