/* eslint-disable @typescript-eslint/naming-convention */
export const MessageConstant = {
  vi: {
    MSG_ERR_SYSTEM: 'Có lỗi xảy ra!',
    MSG_CREATED_DONE: 'Tạo mới thành công!',
    MSG_UPDATED_DONE: 'Cập nhật thông tin thành công!',
    MSG_DELETED_DONE: 'Xóa thành công!',
    MSG_UPLOADED_DONE: 'Upload File lên hệ thống thành công!',
    MSG_UPLOADED_TEMP_DONE: 'Upload File vào thư mục tạm thành công!',
    MSG_DEACTIVE_DONE: 'Chuyển trạng thái thành công',
    MSG_CONFIRM_DEL: 'Bạn có chắc muốn xóa dữ liệu này?',
    MSG_CONFIRM_DEACTIVE: 'Bạn có chắc muốn chuyển trạng thái đối tượng này?',
    MSG_CONFIRM_DEACTIVE_TITLE: 'Xác nhận thay đổi trạng thái',
    XAC_NHAN_XOA: 'Xác nhận xóa',
    MSG_INTERNET_REFUSE: 'Không kết nối được với server',
    MSG_SERVER_REFUSE: 'Mất kết nối internet, vui lòng kiểm tra lại!',
    MSG_ERROR_LOGIN: 'Vui lòng đăng nhập!',
    MSG_TIMEOUT: 'Bạn đã hết phiên đăng nhập!',
    BTN_OK: 'OK',
    BTN_CANCEL: 'Huỷ',
    MSG_ERROR_AUTH: 'Tài khoản không đúng hoặc không có quyền truy cập.',
    MSG_ERR_AUTH: 'Tài khoản không có quyền truy cập.',
    MSG_LOGIN_OK: 'Đăng nhập thành công',
    MSG_WRONG_ACCOUNT: 'Tài khoản hoặc mật khẩu không đúng, vui lòng kiểm tra lại.',
    MSG_WRONG_ACCOUNT_GOOGLE: 'Thông tin tài khoản chưa có trên hệ thống, vui lòng đăng ký trước.',
    MSG_WRONG_ACCOUNT_FACEBOOK: 'Thông tin tài khoản chưa có trên hệ thống, vui lòng đăng ký trước.',
    MSG_TU_CHOI_DUYET: 'Đã từ chối bản thảo!',
    MSG_TU_CHOI_PHAN_BiEN: 'Đã từ chối phản biện bài viết!',
    MSG_DONG_Y_PHAN_BiEN: 'Đã đồng ý phản biện bài viết!',
    MSG_REGISTER_DONE: 'Đăng ký tài khoản thành công!',
    MSG_GUI_BAI_VIET_DONE: 'Đã gửi bài viết thành công!',
    MSG_SUA_BAI_VIET_DONE: 'Đã chỉnh sửa bài viết thành công!',
    MSG_PHAN_BIEN_DONE: 'Đã gửi phản biện thành công!',
    MSG_YEU_CAU_CHINH_SUA: 'Đã gửi yêu cầu chỉnh sửa thành công!',
    MSG_DUYET_DANH_SACH_PHAN_BIEN: 'Duyệt danh sách phản biện thành công!',
    MSG_KHONG_DUYET_DANH_SACH_PHAN_BIEN: 'Đã từ chối Danh sách phản biện!',
    MSG_XOA_DANH_SACH_PHAN_BIEN: 'Đã xoá Danh sách phản biện!',
    MSG_GUI_EMAIL_DONE: 'Đã gửi email thành công!',
    MSG_DUYET_DANG_DONE: 'Duyệt đăng thành công! Tiếp theo, hãy cập nhật số đăng dự kiến cho bài viết này!',
    MSG_NEED_DOCTORATE_OR_HIGHER: 'Đăng ký làm người phản biện cần học vị Tiến Sĩ trở lên!',
    MSG_APPROVE_DONE: 'Đã duyệt thành công!',
    MSG_HUY_DUYET_DANG_DONE: 'Đã huỷ trạng thái duyệt đăng bài viết!',
    MSG_NEED_SELECT_REVIEW_TIMEOUT: 'Thời gian gia hạn phản biện không hợp lệ!',
    MSG_NEED_SELECT_EDIT_TIMEOUT: 'Vui lòng gia hạn thời gian chỉnh sửa!',
    MSG_CHUA_HOAN_THANH_LINH_VUC: 'Vui lòng kiểm tra lại Hướng nghiên cứu chưa hoàn tất!',
    MSG_FIELD_EMPTY: 'Vui lòng điền đủ các mục bắc buộc',
    MGS_APPROVAL_SUCCESS: 'Kiểm duyệt thành công!',
    MGS_PLEASE_SELECT_TOPIC: 'Vui lòng chọn đề tài',
    MGS_PLEASE_UPLOAD_FILE: 'Vui lòng upload file',
    MGS_SUGGESTED_SUCCESS: 'Đề xuất thành công',

  },
  en: {
    MSG_ERR_AUTH: 'Access is denied!',
    MSG_LOGIN_OK: 'Login successfully!',
    MSG_ERR_SYSTEM: 'Something went wrong!',
    MSG_REGISTER_DONE: 'Registration successfully!',
    MSG_NEED_DOCTORATE_OR_HIGHER: 'To register as Reviewer, you need Doctorate Rank or higher!',
    MSG_CREATED_DONE: 'Created successfully!',
    MSG_UPDATED_DONE: 'Updated successfully!',
    MSG_DELETED_DONE: 'Deleted successfully!',
    MSG_UPLOADED_DONE: 'Uploaded successfully!',
    MSG_UPLOADED_TEMP_DONE: 'Uploaded successfully!',
    MSG_DEACTIVE_DONE: 'Changed status successfully!',
    MSG_CONFIRM_DEL: 'Are you sure to delete?',
    MSG_CONFIRM_DEACTIVE: 'Are you sure to change status?',
    MSG_CONFIRM_DEACTIVE_TITLE: 'Confirm change status',
    XAC_NHAN_XOA: 'Confirm delete',
    MSG_INTERNET_REFUSE: 'Can not connect to server',
    MSG_SERVER_REFUSE: 'No network connection!',
    MSG_ERROR_LOGIN: 'Please login!',
    MSG_TIMEOUT: 'Your session expried!',
    BTN_OK: 'OK',
    BTN_CANCEL: 'Cancel',
    MSG_ERROR_AUTH: 'Your account can not access to this resource',
    MSG_WRONG_ACCOUNT: 'Username or Password is not correct!',
    MSG_WRONG_ACCOUNT_GOOGLE: 'Your account info is not exist!',
    MSG_WRONG_ACCOUNT_FACEBOOK: 'Your account info is not exist!',
    MSG_TU_CHOI_DUYET: 'Rejected this article!',
    MSG_TU_CHOI_PHAN_BiEN: 'Rejected reviewing!',
    MSG_DONG_Y_PHAN_BiEN: 'Accepted this article!',
    MSG_GUI_BAI_VIET_DONE: 'Submit article successfully!',
    MSG_SUA_BAI_VIET_DONE: 'Edit article successfully!',
    MSG_PHAN_BIEN_DONE: 'Reviewed successfully!',
    MSG_YEU_CAU_CHINH_SUA: 'Edit request sent!',
    MSG_DUYET_DANH_SACH_PHAN_BIEN: 'Approved Reviewer list!',
    MSG_KHONG_DUYET_DANH_SACH_PHAN_BIEN: 'Rejected Reviewer list!',
    MSG_XOA_DANH_SACH_PHAN_BIEN: 'Deleted Reviewer list!',
    MSG_GUI_EMAIL_DONE: 'Email sent!',
    MSG_DUYET_DANG_DONE: 'Articles approved to publish! Next, please update Publish number for those!',
    MSG_APPROVE_DONE: 'Approved!',
    MSG_HUY_DUYET_DANG_DONE: 'Undo approved successfully!',
    MSG_NEED_SELECT_REVIEW_TIMEOUT: 'Please select valid extended time for review!',
    MSG_NEED_SELECT_EDIT_TIMEOUT: 'Please select extended time for edit!',
    MSG_CHUA_HOAN_THANH_LINH_VUC: 'A research domain is not finish yet!',
    MSG_FIELD_EMPTY: 'Please complete all required fields',
    MGS_APPROVAL_SUCCESS: 'Approval Success!',
    MGS_PLEASE_SELECT_TOPIC: 'Please select topic',
    MGS_PLEASE_UPLOAD_FILE: 'Please upload file',
    MGS_SUGGESTED_SUCCESS: 'Successful Proposal',
  }
};
