/* eslint-disable @typescript-eslint/naming-convention */
export const MessageTooltipConstant = {
  vi: {
    PLEASE_COMPLETE_SELF_ASSESSMENT_CORRESPONDING_COMPLETED_CONTENT:
      'Vui lòng hoàn thành phần tự đánh giá tương ứng với nội dung đã hoàn thành',
    PERMISSION_EDIT_LATEST_REPORT: 'Được phép chỉnh sửa báo cáo mới nhất',
    NO_PROOF_OF_CONTRACT: 'Chưa có minh chứng họp đồng',
    PLEASE_TURN_OFF_EDIT: 'Vui lòng tắt chức năng edit!',
    DOWNLOAD_FORM: 'Tải xuống biểu mẫu',
    UPLOAD_FILE_PROOF_REPLACEMENT: 'Tải lên tệp minh chứng thay thế',
    VIEW_FILE_PROOF: 'Xem file minh chứng',
    VIEW_DETAIL: 'Xem chi tiết',
    LIST_OF_REQUESTS_TO_CANCEL_THE_TOPIC: 'Danh sách yêu cầu xin hủy đề tài',
    SUBMIT_THE_APPLICATION_FORM_TO_CANCEL_THE_TOPIC: 'Xuất biểu mẫu đơn xin hủy đề tài',
    MINUTES_OF_THE_COUNCIL_WAS_CREATED_DOES_NOT_ALLOW_EDITING:
      'Biên bản hội đồng đã được tạo, không cho phép chỉnh sửa',
    VIEW_DETAIL_AND_APPROVE: 'Xem chi tiết và duyệt',
    CONFIRM_APPROVAL_TO_CANCEL_THE_TOPIC: 'Xác nhận duyệt huỷ đề tài? Thao tác này không thể khôi phục!',
    VIEW_AND_APPROVE: 'Xem và xét duyệt',
    CONTENT_RESEARCH_RESULTS: 'Nội dung kết quả nghiên cứu',
    DOWNLOAD_FORM_10_11: 'Xuất biểu mẫu kiểm tra thông tin kết quả nghiên cứu',
    DONT_HAVE_FORM_10_11: 'Chưa có thông tin kết quả nghiên cứu',
    PLEASE_FILL_IN_ALL_EMPLOYEE_DATA_FIELDS: 'Vui lòng điền đủ các trường dữ liệu của nhân viên!',
    NOT_ENOUGH_MEMBERS: 'Chưa đủ thành viên!',
    NOT_YET_SET_UP: 'Chưa được thiết lập',
    APPROVE_THE_PROPOSAL_OF_THE_ACCEPTANCE_COMMITTEE: 'Duyệt đề xuất hội đồng nghiệm thu',
    UPDATE_THE_ACCEPTANCE_BOARD: 'Cập nhật hội đồng nghiệm thu',
    UPLOAD_PROOF: 'Tải lên minh chứng',
    DOWNLOAD_SCRORECARD_ACCEPTANCE: 'Tải phiếu đánh giá nghiệm thu cho thành viên',
    DOWNLOAD_FEEDBACK_FORM_ACCEPTANCE_BOARD: 'Tải phiếu nhận xét phản biện hội đồng nghiệm thu',
    MEMBER_RECOMMENDATION: 'Đề xuất thành viên',
    VIEW_THE_PROPOSAL_FILE: 'Xem file đề xuất thành viên',
    UPLOAD_THE_PROPOSAL_FILE: 'Upload file đề xuất thành viên',
    NOT_TOPIC_CODE_YET: 'Chưa có mã số đề tài! Không được phép upload minh chứng',
    DOWNLOAD_FORM_CANCEL_TOPIC: 'Tải xuống biểu mẫu xin hủy',
    NOT_TIME_TO_DO_IT_YET: 'Chưa đến thời gian thực hiện',
    VIEW_PROPOSAL_TOPIC: 'Xem chi tiết đề xuất đề tài',
    VIEW_EXPLANATION_TOPIC: 'Xem chi tiết thuyết minh đề tài',
    NOT_HAVE_ACCESS: 'Bạn không có quyền truy cập',
    DOWNLOAD_THE_PROPOSAL_FILE: 'Tải file đề xuất thành viên',
  },

  en: {
    PLEASE_COMPLETE_SELF_ASSESSMENT_CORRESPONDING_COMPLETED_CONTENT:
      'Please complete the self-assessment corresponding to the completed content',
    PERMISSION_EDIT_LATEST_REPORT: 'Permission to edit the latest report',
    NO_PROOF_OF_CONTRACT: 'There is no proof of the contract',
    PLEASE_TURN_OFF_EDIT: 'Please turn off edit',
    DOWNLOAD_FORM: 'Download form',
    UPLOAD_FILE_PROOF_REPLACEMENT: 'Upload file proof replacement',
    VIEW_FILE_PROOF: 'View File Proof',
    VIEW_DETAIL: 'View detail',
    LIST_OF_REQUESTS_TO_CANCEL_THE_TOPIC: 'List of requests to cancel the topic',
    SUBMIT_THE_APPLICATION_FORM_TO_CANCEL_THE_TOPIC: 'Submit the application form to cancel the topic',
    MINUTES_OF_THE_COUNCIL_WAS_CREATED_DOES_NOT_ALLOW_EDITING:
      'Minutes of the council was created, does not allow editing',
    VIEW_DETAIL_AND_APPROVE: 'View detail and approve',
    CONFIRM_APPROVAL_TO_CANCEL_THE_TOPIC: 'Confirm approval to cancel the topic? This action cannot be undone!',
    VIEW_AND_APPROVE: 'View and approve',
    CONTENT_RESEARCH_RESULTS: 'Content research result',
    DOWNLOAD_FORM_10_11: 'Export the form to check information about research results',
    DONT_HAVE_FORM_10_11: 'No information on research results yet',
    PLEASE_FILL_IN_ALL_EMPLOYEE_DATA_FIELDS: 'Please fill in all employee data fields!',
    NOT_ENOUGH_MEMBERS: 'Not enough members!',
    NOT_YET_SET_UP: 'Not yet set up',
    APPROVE_THE_PROPOSAL_OF_THE_ACCEPTANCE_COMMITTEE: 'Approve the proposal of the acceptance committee',
    UPDATE_THE_ACCEPTANCE_BOARD: 'Update the acceptance board',
    UPLOAD_PROOF: 'Upload proof',
    DOWNLOAD_SCRORECARD_ACCEPTANCE: 'Download the acceptance assessment form for members',
    DOWNLOAD_FEEDBACK_FORM_ACCEPTANCE_BOARD: 'Download feedback form acceptance board',
    MEMBER_RECOMMENDATION: 'Member recommendation',
    VIEW_THE_PROPOSAL_FILE: 'View member proposal file',
    UPLOAD_THE_PROPOSAL_FILE: 'Upload member proposal file',
    NOT_TOPIC_CODE_YET: 'No topic code yet! not allowed to upload',
    DOWNLOAD_FORM_CANCEL_TOPIC: 'Download form cancel topic',
    NOT_TIME_TO_DO_IT_YET: 'It is not time to do it yet',
    VIEW_PROPOSAL_TOPIC: 'View proposal topic detail',
    VIEW_EXPLANATION_TOPIC: 'View explanation topic detail',
    NOT_HAVE_ACCESS: 'You do not have access',
    DOWNLOAD_THE_PROPOSAL_FILE: 'Tải member proposal file',
  }
};
